name: Docker Image CI

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    branches: [main]
    types: 
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: target
        path: target

    - name: List target directory
      run: ls -la target
 
    - name: Print current directory
      run: pwd
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

